version: '3.9'

services:
  postgres:
    image: postgres:14-alpine
    ports:
      - 5432:5432
    volumes:
      - ./vpostgres:/var/lib/postgresql
    environment:
      - POSTGRES_PASSWORD=S3cret
      - POSTGRES_USER=admin
      - POSTGRES_DB=Restaurant