global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'dotnet-core-app'
    scrape_interval: 5s
    static_configs:
      - targets: ['host.docker.internal:5010']  # Your app's metrics endpoint