// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using infrastructure.Database.RestaurantContext;

#nullable disable

namespace infrastructure.Database.RestaurantContext.Migrations
{
    [DbContext(typeof(RestaurantDbContext))]
    [Migration("20240813055603_restaurant - init")]
    partial class restaurantinit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("restuarant")
                .HasAnnotation("ProductVersion", "8.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GroupMeal", b =>
                {
                    b.Property<int>("GroupID")
                        .HasColumnType("integer");

                    b.Property<int>("MealsMealID")
                        .HasColumnType("integer");

                    b.HasKey("GroupID", "MealsMealID");

                    b.HasIndex("MealsMealID");

                    b.ToTable("GroupMeal", "menu");
                });

            modelBuilder.Entity("GroupMenu", b =>
                {
                    b.Property<int>("GroupsGroupID")
                        .HasColumnType("integer");

                    b.Property<int>("MenuId")
                        .HasColumnType("integer");

                    b.HasKey("GroupsGroupID", "MenuId");

                    b.HasIndex("MenuId");

                    b.ToTable("GroupMenu", "menu");
                });

            modelBuilder.Entity("IngredientMeal", b =>
                {
                    b.Property<int>("IngredientsIngredientID")
                        .HasColumnType("integer");

                    b.Property<int>("MealID")
                        .HasColumnType("integer");

                    b.HasKey("IngredientsIngredientID", "MealID");

                    b.HasIndex("MealID");

                    b.ToTable("IngredientMeal", "menu");
                });

            modelBuilder.Entity("domain.Menus.Aggregates.Entities.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Menus", "menu");
                });

            modelBuilder.Entity("domain.Menus.ValueObjects.Group", b =>
                {
                    b.Property<int>("GroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GroupID"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GroupID");

                    b.ToTable("Groups", "menu");
                });

            modelBuilder.Entity("domain.Menus.ValueObjects.Ingredient", b =>
                {
                    b.Property<int>("IngredientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IngredientID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IngredientID");

                    b.ToTable("Ingredients", "menu");
                });

            modelBuilder.Entity("domain.Menus.ValueObjects.Meal", b =>
                {
                    b.Property<int>("MealID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MealID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<decimal>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("MealID");

                    b.ToTable("Meals", "menu");
                });

            modelBuilder.Entity("domain.Restaurants.Aggregates.Entities.Owner", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AddressID")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AddressID");

                    b.ToTable("Owners", "restaurant");
                });

            modelBuilder.Entity("domain.Restaurants.Aggregates.Restaurant", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("OpeningHoursID")
                        .HasColumnType("integer");

                    b.Property<int>("OwnerId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("OpeningHoursID");

                    b.HasIndex("OwnerId");

                    b.ToTable("Restaurants", "restaurant");
                });

            modelBuilder.Entity("domain.Restaurants.ValueObjects.Address", b =>
                {
                    b.Property<int>("AddressID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("AddressID"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("AddressID");

                    b.ToTable("Addresses", "restaurant");
                });

            modelBuilder.Entity("domain.Restaurants.ValueObjects.OpeningHours", b =>
                {
                    b.Property<int>("OpeningHoursID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("OpeningHoursID"));

                    b.HasKey("OpeningHoursID");

                    b.ToTable("OpeningHours", "restaurant");
                });

            modelBuilder.Entity("domain.Restaurants.ValueObjects.WorkingDay", b =>
                {
                    b.Property<int>("WorkingDayID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("WorkingDayID"));

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<bool>("Free")
                        .HasColumnType("boolean");

                    b.Property<TimeSpan>("From")
                        .HasColumnType("interval");

                    b.Property<int?>("OpeningHoursID")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("To")
                        .HasColumnType("interval");

                    b.HasKey("WorkingDayID");

                    b.HasIndex("OpeningHoursID");

                    b.ToTable("WorkingDays", "restaurant");
                });

            modelBuilder.Entity("GroupMeal", b =>
                {
                    b.HasOne("domain.Menus.ValueObjects.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("domain.Menus.ValueObjects.Meal", null)
                        .WithMany()
                        .HasForeignKey("MealsMealID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupMenu", b =>
                {
                    b.HasOne("domain.Menus.ValueObjects.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsGroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("domain.Menus.Aggregates.Entities.Menu", null)
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IngredientMeal", b =>
                {
                    b.HasOne("domain.Menus.ValueObjects.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("IngredientsIngredientID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("domain.Menus.ValueObjects.Meal", null)
                        .WithMany()
                        .HasForeignKey("MealID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("domain.Restaurants.Aggregates.Entities.Owner", b =>
                {
                    b.HasOne("domain.Restaurants.ValueObjects.Address", "Address")
                        .WithMany()
                        .HasForeignKey("AddressID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");
                });

            modelBuilder.Entity("domain.Restaurants.Aggregates.Restaurant", b =>
                {
                    b.HasOne("domain.Restaurants.ValueObjects.OpeningHours", "OpeningHours")
                        .WithMany()
                        .HasForeignKey("OpeningHoursID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("domain.Restaurants.Aggregates.Entities.Owner", "Owner")
                        .WithMany()
                        .HasForeignKey("OwnerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("OpeningHours");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("domain.Restaurants.ValueObjects.Address", b =>
                {
                    b.OwnsOne("domain.Restaurants.ValueObjects.Coordinates", "Coordinates", b1 =>
                        {
                            b1.Property<int>("AddressID")
                                .HasColumnType("integer");

                            b1.Property<double>("X")
                                .HasColumnType("double precision");

                            b1.Property<double>("Y")
                                .HasColumnType("double precision");

                            b1.HasKey("AddressID");

                            b1.ToTable("Addresses", "restaurant");

                            b1.WithOwner()
                                .HasForeignKey("AddressID");
                        });

                    b.Navigation("Coordinates")
                        .IsRequired();
                });

            modelBuilder.Entity("domain.Restaurants.ValueObjects.WorkingDay", b =>
                {
                    b.HasOne("domain.Restaurants.ValueObjects.OpeningHours", null)
                        .WithMany("WorkingDays")
                        .HasForeignKey("OpeningHoursID");
                });

            modelBuilder.Entity("domain.Restaurants.ValueObjects.OpeningHours", b =>
                {
                    b.Navigation("WorkingDays");
                });
#pragma warning restore 612, 618
        }
    }
}
