// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using infrastructure.Database.MenuContext;

#nullable disable

namespace infrastructure.Database.MenuContext.Migrations
{
    [DbContext(typeof(MenuDbContext))]
    [Migration("20250423160503_categoryId")]
    partial class categoryId
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("menu")
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GroupMeals", b =>
                {
                    b.Property<int>("GroupID")
                        .HasColumnType("integer");

                    b.Property<int>("MealID")
                        .HasColumnType("integer");

                    b.HasKey("GroupID", "MealID");

                    b.HasIndex("MealID");

                    b.ToTable("GroupMeals", "menu");
                });

            modelBuilder.Entity("GroupMenu", b =>
                {
                    b.Property<int>("GroupsGroupID")
                        .HasColumnType("integer");

                    b.Property<int>("MenuId")
                        .HasColumnType("integer");

                    b.HasKey("GroupsGroupID", "MenuId");

                    b.HasIndex("MenuId");

                    b.ToTable("GroupMenu", "menu");
                });

            modelBuilder.Entity("MealCategories", b =>
                {
                    b.Property<int>("CategoryID")
                        .HasColumnType("integer");

                    b.Property<int>("MealID")
                        .HasColumnType("integer");

                    b.HasKey("CategoryID", "MealID");

                    b.HasIndex("MealID");

                    b.ToTable("MealCategories", "menu");
                });

            modelBuilder.Entity("MealIngredients", b =>
                {
                    b.Property<int>("GroupID")
                        .HasColumnType("integer");

                    b.Property<int>("MealID")
                        .HasColumnType("integer");

                    b.HasKey("GroupID", "MealID");

                    b.HasIndex("MealID");

                    b.ToTable("MealIngredients", "menu");
                });

            modelBuilder.Entity("domain.Menus.Aggregates.Entities.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Categories", "menu");
                });

            modelBuilder.Entity("domain.Menus.Aggregates.Menu", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Restaurant")
                        .HasColumnType("integer")
                        .HasColumnName("RestaurantID");

                    b.HasKey("Id");

                    b.ToTable("Menus", "menu");
                });

            modelBuilder.Entity("domain.Menus.ValueObjects.Group", b =>
                {
                    b.Property<int>("GroupID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("GroupID"));

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("GroupID");

                    b.ToTable("Groups", "menu");
                });

            modelBuilder.Entity("domain.Menus.ValueObjects.Ingredient", b =>
                {
                    b.Property<int>("IngredientID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("IngredientID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("IngredientID");

                    b.ToTable("Ingredients", "menu");
                });

            modelBuilder.Entity("domain.Menus.ValueObjects.Meal", b =>
                {
                    b.Property<int>("MealID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("MealID"));

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<decimal?>("Price")
                        .HasColumnType("numeric");

                    b.HasKey("MealID");

                    b.ToTable("Meals", "menu");
                });

            modelBuilder.Entity("domain.Menus.ValueObjects.MenuRestaurant", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer");

                    b.HasKey("Id")
                        .HasName("RestaurantID");

                    b.ToTable("Restaurants", "menu");
                });

            modelBuilder.Entity("GroupMeals", b =>
                {
                    b.HasOne("domain.Menus.ValueObjects.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("domain.Menus.ValueObjects.Meal", null)
                        .WithMany()
                        .HasForeignKey("MealID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("GroupMenu", b =>
                {
                    b.HasOne("domain.Menus.ValueObjects.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupsGroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("domain.Menus.Aggregates.Menu", null)
                        .WithMany()
                        .HasForeignKey("MenuId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MealCategories", b =>
                {
                    b.HasOne("domain.Menus.ValueObjects.Meal", null)
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("domain.Menus.Aggregates.Entities.Category", null)
                        .WithMany()
                        .HasForeignKey("MealID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MealIngredients", b =>
                {
                    b.HasOne("domain.Menus.ValueObjects.Meal", null)
                        .WithMany()
                        .HasForeignKey("GroupID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("domain.Menus.ValueObjects.Ingredient", null)
                        .WithMany()
                        .HasForeignKey("MealID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
